name: Deployment
on: 
  push:
    branches:
      - master
  pull_request:
    types: [closed]
jobs:
    build:
        name: shinyapps
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, 'ci skip')"
        steps:
            - uses: actions/checkout@v1
            - uses: ./.github/actions/deployment
              env:
                SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
                SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}