name: Deployment workflow
on: push
jobs:
    build:
        name: shinyapps deployment
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: ./.github/actions/deployment
              env:
                SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
                SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}